### ISSUE TITLE
site bboxes_utils.py issue

### ISSUE THREAD

**Issue by jinymusim** [ufal/npfl114#118]
Sites hyperlink for bboxes_utils.py doesn't work. It gives out 404 error as lab06 doesn't contain the script.

**Comment by foxik** [comment]
Hi,

that is currently a feature -- I am finalizing the template and will publish it during today; but I agree that I could have said that in the task description -- will update it after the English practicals.

**Comment by foxik** [comment]
Warning added in [217d293](https://github.com/ufal/npfl114/commit/217d2935e3ebf9378d979d62c1cdb8e1b1f86177).
