### ISSUE TITLE
Change the code to fetch data from the .tfrecord files

### ISSUE THREAD

**Issue by jren2017** [ufal/npfl114#4]
https://github.com/ufal/npfl114/blob/master/labs03/1-mnist.py

Hello, I tried to change your code to use the .tfrecord as data source file. but it doesm't work, can you help solve my problem? I put a question on the stackoverflow

https://stackoverflow.com/questions/46985411/tensorflow-read-tfrecord-without-a-graph

**Comment by foxik** [comment]
The code in this repository was written for TensorFlow 0.11, and is surely broken with current TF version. 

The code will be be updated to latest TF when next university course starts, in February 2018. Until then, there will be no/little changes in the repository.
