### ISSUE TITLE
Site redirects to old year

### ISSUE THREAD

**Issue by jinymusim** [ufal/npfl114#87]
In the assignment tab, in the section for sgd_manual, hyper link for sgd_backpropagation redirects to former year of this course 
( the link: https://ufal.mff.cuni.cz/courses/npfl114/2021-summer#sgd_backpropagation)
It should redirect to current year course so to https://ufal.mff.cuni.cz/courses/npfl114/2022-summer#sgd_backpropagation
or something in that nature.

**Comment by foxik** [comment]
Ah, definitely, I forgot I need to update also the targets containing the previous school year -- I have now updated the targets in all the assignments from the last year, including this one. Thanks, a community-work point is heading you way, cheers!

**Comment by foxik** [comment]
Fixed in d3b2b5c.
